### ISSUE TITLE
error during run 'python setup.py install'

### ISSUE THREAD

**Issue by liu824** [frostinassiky/gtad#19]
running install
running bdist_egg
running egg_info
writing Align1D.egg-info\PKG-INFO
writing dependency_links to Align1D.egg-info\dependency_links.txt
writing top-level names to Align1D.egg-info\top_level.txt
reading manifest file 'Align1D.egg-info\SOURCES.txt'
writing manifest file 'Align1D.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'Align1D' extension
Emitting ninja build file E:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc "-ID:\Program Files\anaconda\lib\site-packages\torch\include" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\torch\csrc\api\include" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\TH" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\THC" "-ID:\Program Files\anaconda\include" "-ID:\Program Files\anaconda\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c E:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\Align1D_cuda.cpp /FoE:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\build\temp.win-amd64-3.7\Release\Align1D_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=Align1D -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: E:/machineLearning/天池视频时序事件检测/gtad-master/gtad-master/gtad_lib/build/temp.win-amd64-3.7/Release/Align1D_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc "-ID:\Program Files\anaconda\lib\site-packages\torch\include" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\torch\csrc\api\include" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\TH" "-ID:\Program Files\anaconda\lib\site-packages\torch\include\THC" "-ID:\Program Files\anaconda\include" "-ID:\Program Files\anaconda\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c E:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\Align1D_cuda.cpp /FoE:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\build\temp.win-amd64-3.7\Release\Align1D_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=Align1D -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: 句柄无效。

Traceback (most recent call last):
  File "D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "D:\Program Files\anaconda\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    'build_ext': BuildExtension
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "D:\Program Files\anaconda\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files\anaconda\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Program Files\anaconda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Program Files\anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\anaconda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "D:\Program Files\anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\anaconda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Program Files\anaconda\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Program Files\anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\anaconda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Program Files\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Program Files\anaconda\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Program Files\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "D:\Program Files\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Program Files\anaconda\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\Program Files\anaconda\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by frostinassiky** [comment]
Hi @liu824 Thanks for your interest in G-TAD!

I haven't run G-TAD on any window machine. Thank for sharing the error log!

It **seems** some files are missing, leading to the "CreateProcess failure". Does E:\machineLearning\天池视频时序事件检测\gtad-master\gtad-master\gtad_lib\build\temp.win-amd64-3.7\Release\Align1D_cuda.obj exists?
